---
title: Giorgio
permalink: pretty

author:
  name: Giorgio
  email: parlato.giorgio@gmail.com

minima:
  skin: giorgio

  social_links:
    twitter: giorgiop_
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

collections:
  blog:
    output: true

defaults:
  - scope:
      path: "_blog/*/*.*"
    values:
      layout: post

  - scope:
      path: "_blog/letters/*.*"
    values:
      category: letters

  - scope:
      path: "_blog/writing/*.*"
    values:
      category: writing

# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  collection: 'blog'
  permalink: '/page/:num/'
  # title: ':title - page :num'
  sort_reverse: true
  per_page: 10

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - HOWTO.md
  - README.md
