---
title: Giorgio – Exploring Ideas
# description: "Born and raised in Sicily, I spent the last five years in the US and Asia, and I’m currently based in Stockholm. I have a degree in Economics and an MBA with a focus on sustainability. My interests are mostly around meditation, regenerative agriculture, community, and entrepreneurship, and recently I’ve been fascinated to learn about Complexity Science."

author:
  name: Giorgio
  email: parlato.giorgio@gmail.com

description: "Born and raised in Sicily, I spent the last five years in the US and Asia, and I’m currently based in Stockholm. I have a degree in Economics and an MBA with a focus on sustainability.
My interests are mostly around meditation, regenerative agriculture, community, and entrepreneurship, and recently I’ve been fascinated to learn about Complexity Science."

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: giorgiop_
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
#
collections:
  blog:
    output: true

defaults:
  - scope:
      path: "_blog/*/*.*"
    values:
      layout: post

  - scope:
      path: "_blog/letters/*.*"
    values:
      category: letters

  - scope:
      path: "_blog/writings/*.*"
    values:
      category: writings

# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  collection: 'blog'
  permalink: '/page/:num/'
  # title: ':title - page :num'
  sort_reverse: true
  per_page: 10

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - HOWTO.md
  - README.md
